import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import FeaturedCollection from "../components/featuredcollection";

export default function Home({ data }) {
  return (
    <div className="pt-20 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedCollection tshirts={data} />
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetch(`${process.env.NEXT_PUBLIC_BACK_URL}/api/tshirts/?populate=*`);
  const data_res = await data.json();

  return {
    props: data_res,
  };
}
