import React from "react";
import Head from "next/head";

export default function About() {
  return (
    <div className="p-5 box-border h-full pt-28 min-h-screen">
      <Head>
        <title>Return Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-5  rounded  shadow p-2">
        <h1 className="text-5xl  text-center">Return Policy</h1>
        <hr />
        <p className="text-justify ">
          Hello and welcome to my website Hello and welcome to my website Hello
          and welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website Hello and
          welcome to my website Hello and welcome to my website
        </p>
      </div>
    </div>
  );
}